-- MySQL Script generated by MySQL Workbench
-- 07/20/14 16:45:42
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema docsdig
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `docsdig` DEFAULT CHARACTER SET latin1 ;
USE `docsdig` ;

-- -----------------------------------------------------
-- Table `docsdig`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `docsdig`.`empresas` (
  `id_empresa` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `borrado` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`id_empresa`, `nombre`),
  UNIQUE INDEX `id_empresa_UNIQUE` (`id_empresa` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `docsdig`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `docsdig`.`sucursales` (
  `id_sucursal` INT(11) NOT NULL AUTO_INCREMENT,
  `id_empresa` INT(11) NOT NULL,
  `nombre` VARCHAR(250) NOT NULL,
  `calle` VARCHAR(255) NULL DEFAULT NULL,
  `colonia` VARCHAR(45) NULL DEFAULT NULL,
  `num_ext` INT(11) NULL DEFAULT NULL,
  `num_int` INT(11) NULL DEFAULT NULL,
  `codigo_postal` INT(11) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_creador` INT(11) NULL DEFAULT NULL,
  `fecha_modificacion` TIMESTAMP NULL DEFAULT NULL,
  `usuario_modificador` INT(11) NULL DEFAULT NULL,
  `borrado` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`id_sucursal`),
  UNIQUE INDEX `id_sucursal_UNIQUE` (`id_sucursal` ASC),
  INDEX `_idx` (`id_empresa` ASC),
  CONSTRAINT `fk_id_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `docsdig`.`empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `docsdig`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `docsdig`.`empleados` (
  `id_empelado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `rfc` VARCHAR(13) NOT NULL,
  `puesto` VARCHAR(115) NULL DEFAULT NULL,
  `id_sucursal` INT(11) NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_creador` INT(11) NULL DEFAULT NULL,
  `fecha_modificacion` TIMESTAMP NULL DEFAULT NULL,
  `usuario_modificador` INT(11) NULL DEFAULT NULL,
  `borrado` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`id_empelado`),
  UNIQUE INDEX `id_empelado_UNIQUE` (`id_empelado` ASC),
  INDEX `fk_id_sucursal_idx` (`id_sucursal` ASC),
  CONSTRAINT `fk_id_sucursal`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `docsdig`.`sucursales` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `docsdig`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `docsdig`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `correo_electronico` VARCHAR(250) NOT NULL,
  `rfc` VARCHAR(13) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `id_empresa` INT(11) NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `borrado` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC),
  INDEX `id_empresa_idx` (`id_empresa` ASC),
  CONSTRAINT `id_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `docsdig`.`empresas` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;

USE `docsdig` ;

-- -----------------------------------------------------
-- procedure SP_INS_EMPLEADO
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INS_EMPLEADO`(
	IN pi_nombre VARCHAR(250),
	IN pi_rfc VARCHAR(13),
	IN pi_puesto VARCHAR(115),
	IN pi_id_sucursal INT
)
BEGIN
	INSERT INTO empleados (nombre, rfc, puesto, id_sucursal, borrado) VALUES(pi_nombre, pi_rfc, pi_puesto, pi_id_sucursal, 0);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_INS_EMPRESA
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INS_EMPRESA`(
IN pi_nombre VARCHAR(250),
OUT po_id_empresa INT
)
BEGIN
	INSERT INTO empresas (nombre, borrado) VALUES(pi_nombre, 0);
	SET po_id_empresa = LAST_INSERT_ID();
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_INS_EMPRESA_USUARIO
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INS_EMPRESA_USUARIO`(
	IN pi_nombre_usuario VARCHAR(250),
	IN pi_correo_electronico VARCHAR(250),
	IN pi_rfc VARCHAR(13),
	IN pi_contrasena VARCHAR(100),
	IN pi_nombre_empresa VARCHAR(250)
)
BEGIN
	
	DECLARE id_empresa int;

	START TRANSACTION;
		-- Insertar Empresa y regresa el id
		CALL docsdig.SP_INS_EMPRESA(pi_nombre_empresa, @po_id_empresa);		
		SET id_empresa = (SELECT @po_id_empresa);
		
		-- Insertar el usuario
		CALL docsdig.SP_INS_USUARIO(pi_nombre_usuario, pi_correo_electronico, pi_rfc, pi_contrasena, id_empresa);
		
	COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_INS_SUCURSAL
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INS_SUCURSAL`(
	IN pi_id_empresa INT,
	IN pi_nombre VARCHAR(250),
	IN pi_calle VARCHAR(255),
	IN pi_colonia VARCHAR(45),
	IN pi_num_ext INT,
	IN pi_num_int INT,
	IN pi_cp INT,
	IN pi_ciudad VARCHAR(45),
	IN pi_pais VARCHAR(45)
)
BEGIN
	INSERT INTO 
		sucursales (id_empresa, nombre, calle, colonia, num_ext, num_int, codigo_postal, ciudad, pais, borrado ) 
		VALUES (pi_id_empresa, pi_nombre, pi_calle, pi_colonia, pi_num_ext, pi_num_int, pi_cp, pi_ciudad, pi_pais, 0);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_INS_USUARIO
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INS_USUARIO`(
IN pi_nombre VARCHAR(250),
IN pi_correo_electronico VARCHAR(250),
IN pi_rfc VARCHAR(13),
IN pi_contrasena VARCHAR(100),
IN pi_id_empresa INT
)
BEGIN
	INSERT INTO 
		usuarios (nombre, correo_electronico, rfc, contrasena, id_empresa, borrado ) 
		VALUES (pi_nombre, pi_correo_electronico, pi_rfc, pi_contrasena, pi_id_empresa, 0);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_LOGIN
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_LOGIN`(
	IN pi_correo_electronico VARCHAR(250),
	IN pi_contrasena VARCHAR(100)
)
BEGIN
	SELECT 
		usr.id_usuario,
		usr.nombre,
		usr.rfc,
		usr.correo_electronico,
		usr.id_empresa,
		emp.nombre AS empresa
	FROM 
		usuarios usr
		INNER JOIN empresas emp ON usr.id_empresa = emp.id_empresa
	WHERE 
		usr.correo_electronico = pi_correo_electronico 
		AND usr.contrasena = pi_contrasena;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_SEL_EMPLEADOS_POR_EMPRESA
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_EMPLEADOS_POR_EMPRESA`(
	IN pi_id_empresa INT
)
BEGIN
	SELECT 
		emp.id_empelado,
		emp.nombre,
		emp.rfc,
		emp.puesto,
		emp.id_sucursal,
		suc.nombre AS sucursal
	FROM 
		docsdig.empleados emp
		INNER JOIN docsdig.sucursales suc ON emp.id_sucursal = suc.id_sucursal
		INNER JOIN docsdig.usuarios usr ON usr.id_empresa = suc.id_empresa
	WHERE
		usr.id_empresa = pi_id_empresa;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_SEL_EMPRESA_POR_NOMBRE
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_EMPRESA_POR_NOMBRE`(
	IN pi_nombre VARCHAR(250)
)
BEGIN
	SELECT COUNT(*) FROM docsdig.empresas WHERE nombre = pi_nombre;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_SEL_SUCURSALES_POR_ID_EMPRESA
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_SUCURSALES_POR_ID_EMPRESA`(
	IN pi_id_empresa INT
)
BEGIN
	SELECT 
		s.id_empresa,
		s.id_sucursal, 
		s.nombre, 
		s.calle, 
		s.colonia, 
		s.num_ext, 
		s.num_int, 
		s.codigo_postal,
		s.ciudad,
		s.pais,
		(SELECT COUNT(*) FROM docsdig.empleados WHERE id_sucursal = s.id_sucursal) AS no_empleados 
	FROM 
		docsdig.sucursales s
	WHERE
		s.id_empresa = pi_id_empresa;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_SEL_SUCURSAL_POR_NOMBRE
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_SUCURSAL_POR_NOMBRE`(
	IN pi_nombre VARCHAR(250),
	IN pi_id_empresa INT
)
BEGIN
	SELECT COUNT(*) FROM docsdig.sucursales WHERE nombre = pi_nombre AND id_empresa = pi_id_empresa;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_SEL_USUARIOS_CORREO
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_USUARIOS_CORREO`(
	IN pi_correo_electronico VARCHAR(250)
)
BEGIN
	SELECT COUNT(*) FROM docsdig.usuarios WHERE correo_electronico = pi_correo_electronico;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SP_SEL_USUARIO_POR_CORREO
-- -----------------------------------------------------

DELIMITER $$
USE `docsdig`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SEL_USUARIO_POR_CORREO`(
	IN pi_correo_electronico VARCHAR(250)
)
BEGIN
	SELECT 
		usr.id_usuario,
		usr.nombre,
		usr.correo_electronico,
		usr.rfc,
		usr.id_empresa,
		emp.nombre AS empresa
	FROM 
		docsdig.usuarios usr
		INNER JOIN docsdig.empresas emp ON  usr.id_empresa = emp.id_empresa
	WHERE
		usr.borrado = 0
		AND usr.correo_electronico = pi_correo_electronico;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
